#!/usr/bin/env python3

import sys, os, re

def help():
    string = """
    Usage: %s [FILE]
    Remove numeric prefixes from FILE.

    With no FILE, or when FILE is -, read standard input.

    Examples:
      uniq -c raw.txt | sort -nr | %s - > sorted-by-range.txt
    """
    string = string.replace("%s", sys.argv[0])
    string = string.replace(os.linesep + "    ", os.linesep)
    string = os.linesep.join(string.split(os.linesep)[1:-1])
    print(string)
    sys.exit(0)

# handle reading from stdin
stdin = "/dev/stdin"
if len(sys.argv) == 1 and not sys.stdin.isatty():
    sys.argv.append(stdin)
elif len(sys.argv) == 2 and sys.argv[1] == "-":
    sys.argv[1] = stdin

if len(sys.argv) != 2 or not os.path.exists(sys.argv[1]):
    help()

# regex to extract line contents without numeric prefix
regex = re.compile(b"^\s*[0-9]+\s(.+?)?$")

input_file = open(sys.argv[1], 'rb')

lineno = 1
while True:
    line = input_file.readline()
    if not line:
        break
    try:
        word = regex.findall(line)[0]
    except IndexError:
        sys.exit("ERROR: No numeric prefix at line %d" % lineno)
    lineno += 1
    sys.stdout.buffer.write(word + b"\n")
