#!/usr/bin/env python3

import sys

if len(sys.argv) == 3 and not sys.stdin.isatty():
    sys.argv.append("/dev/stdin")
elif len(sys.argv) == 4 and sys.argv[3] == "-":
    sys.argv[3] = "/dev/stdin"

try:
    assert len(sys.argv) == 4
    minval, maxval = sorted([int(sys.argv[1]), int(sys.argv[2])])
    input_file = open(sys.argv[3], 'rb')
except:
    print("Usage: %s <minrange> <maxrange> <file>")

while True:
    line = input_file.readline()
    if not line:
        break
    if minval <= int(line.split(b" ", 1)[0]) <= maxval:
        sys.stdout.buffer.write(line)
