#!/usr/bin/env python3

import sys, os

if len(sys.argv) == 1 and not sys.stdin.isatty():
    sys.argv.append("/dev/stdin")
elif len(sys.argv) == 2 and sys.argv[1] == "-":
    sys.argv[1] = "/dev/stdin"

if len(sys.argv) != 2 or not os.path.exists(sys.argv[1]):
    sys.exit("Usage: %s <wordlist>" % sys.argv[0])


input_file = open(sys.argv[1], 'rb')
stats = dict.fromkeys(range(100000), 0)

while True:
    line = input_file.readline()
    if not line:
        break
    stats[len(line.splitlines()[0])] += 1

for length, occurences in stats.items():
    if occurences > 0:
        print("length %d\t= %d" % (length, occurences))
