#!/usr/bin/env python3

import sys, os, re

if len(sys.argv) == 1 and not sys.stdin.isatty():
    sys.argv.append("/dev/stdin")
elif len(sys.argv) == 2 and sys.argv[1] == "-":
    sys.argv[1] = "/dev/stdin"

if len(sys.argv) != 2 or not os.path.isfile(sys.argv[1]):
    sys.exit("Usage: %s <occurences-prefixed-wordlist.txt>")

regex = re.compile(b"^\s*([0-9]+)\s+(.+?)?$")
input_file = open(sys.argv[1], 'rb')

while True:
    line = input_file.readline()
    if not line:
        break
    parsed = regex.findall(line)[0]
    assert len(parsed) == 2
    repeat = int(parsed[0])
    word = parsed[1]
    sys.stdout.buffer.write((word + b"\n") * repeat)
